//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace EurocopterFollowUp.DAL.Eurocopter
{
    public partial class EurocopterEntities : DbContext
    {
        public EurocopterEntities()
            : base("name=EurocopterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ApplicationRole> ApplicationRoles { get; set; }
        public DbSet<ApplicationUsersInRole> ApplicationUsersInRoles { get; set; }
        public DbSet<vw_UserDetails> vw_UserDetails { get; set; }
        public DbSet<vw_aspnet_Users_Synonim> vw_aspnet_Users_Synonim { get; set; }
        public DbSet<GridState> GridStates { get; set; }
        public DbSet<ItemStatusHistory> ItemStatusHistories { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<Item> Items { get; set; }
    }
}
