//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EurocopterFollowUp.DAL.Eurocopter
{
    public partial class ItemStatusHistory
    {
        public System.Guid Id { get; set; }
        public System.Guid ItemId { get; set; }
        public short FromStatusId { get; set; }
        public short ToStatusId { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual ItemStatusHistory ItemStatusHistory1 { get; set; }
        public virtual ItemStatusHistory ItemStatusHistory2 { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Item Item { get; set; }
    }
    
}
