//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EurocopterFollowUp.DAL.Eurocopter
{
    public partial class Item
    {
        public Item()
        {
            this.ItemStatusHistories = new HashSet<ItemStatusHistory>();
        }
    
        public System.Guid Id { get; set; }
        public string WO { get; set; }
        public string WP { get; set; }
        public string Ud { get; set; }
        public string Subsystem_ECP { get; set; }
        public string Issue { get; set; }
        public string Installation { get; set; }
        public string RPT_VCI { get; set; }
        public string Indice { get; set; }
        public string Designation { get; set; }
        public string Type { get; set; }
        public string TypeIU { get; set; }
        public string ConfNo { get; set; }
        public string Effectivity { get; set; }
        public string Aircraft { get; set; }
        public System.DateTime DataIn { get; set; }
        public System.DateTime Deadline { get; set; }
        public Nullable<System.DateTime> DataOut { get; set; }
        public string DaosDescription { get; set; }
        public string Daos { get; set; }
        public Nullable<System.Guid> AuthorId { get; set; }
        public short StatusId { get; set; }
        public string Comment { get; set; }
        public Nullable<System.Guid> ProofReaderId { get; set; }
        public decimal AuthoringPercent { get; set; }
        public decimal CrossCheckPercent { get; set; }
        public decimal FinalPercent { get; set; }
        public string Figure { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual ICollection<ItemStatusHistory> ItemStatusHistories { get; set; }
    }
    
}
