//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EurocopterFollowUp.DAL.Eurocopter
{
    public partial class vw_UserDetails
    {
        public long UserDetailsId { get; set; }
        public System.Guid UserId { get; set; }
        public string UserFullName { get; set; }
    }
    
}
